
class GON_PARTICIPANT_TYPE:
    COMMUNITY = 'COMMUNITY'
    PRE_SEEDER = 'PRE_SEEDER'
    LP_PROVIDER = 'LP_PROVIDER'
    FOUNDING_TEAM = 'FOUNDING_TEAM'

class GON_PARTICIPANT_ACTION_TYPE:
    DEPOSIT = 'DEPOSIT'
    WITHDRAW = 'WITHDRAW'
    INVEST_IN_STRATEGY = 'INVEST_IN_STRATEGY'
    UNVEST_IN_STRATEGY = 'UNVEST_IN_STRATEGY'
    WITHDRAW_REWARDS_FROM_STRATEGY = 'WITHDRAW_REWARDS_FROM_STRATEGY'
    RECORD_REWARDS_ON_STRATEGY = 'RECORD_REWARDS_ON_STRATEGY'
    SWAP= 'SWAP'
    ADD_AMM_LIQUIDITY = 'ADD_AMM_LIQUIDITY'
    REMOVE_AMM_LIQUDITY = 'REMOVE_AMM_LIQUDITY'
    RECORD_REWARDS_ON_LP = 'RECORD_REWARDS_ON_LP'
    AMM_TRADE_FEES = 'AMM_TRADE_FEES'
    RECORD_REWARDS_ON_FOUNDERS = 'RECORD_REWARDS_ON_FOUNDERS'
    RECORD_REWARDS_ON_SEEDERS = 'RECORD_REWARDS_ON_SEEDERS'
    #SWAP = 'TRADE'
    #STAKE = 'STAKE'
    #UNSTAKE = 'UNSTAKE'
    BUY_AND_BURN = 'BUY_AND_BURN'

class GON_PM_TYPE:
    SIMPLE = 'SIMPLE'
    SIMPLE_PP = 'SIMPLE_PP'
    CONSERVATIVE = 'CONSERVATIVE'
    BUY_AND_HOLD = 'BUY_AND_HOLD'
    LP_PROVIDER = 'LP_PROVIDER'
    SOPHISTICATED = 'SOPHISTICATED'
    PRE_SEEDER = 'PRE_SEEDER'
    FOUNDING_TEAM = 'FOUNDING_TEAM'

    @staticmethod
    def to_dict():
        return {'SIMPLE': GON_PM_TYPE.SIMPLE,
                'SIMPLE_PP': GON_PM_TYPE.SIMPLE_PP,
                'CONSERVATIVE': GON_PM_TYPE.CONSERVATIVE,
                'BUY_AND_HOLD': GON_PM_TYPE.BUY_AND_HOLD,
                'LP_PROVIDER': GON_PM_TYPE.LP_PROVIDER,
                'SOPHISTICATED': GON_PM_TYPE.SOPHISTICATED,}


# class GON_PM_TYPE:
#     SIMPLE = 'SIMPLE'
#     SIMPLE_WITH_PROFIT_TAKING_ON_APY = 'SIMPLE_WITH_PROFIT_TAKING_ON_APY'
#     CONSERVATIVE = 'CONSERVATIVE'
#     BUY_AND_HOLD = 'BUY_AND_HOLD'
#     LP_PROVIDER = 'LP_PROVIDER'
#     SOPHISTICATED = 'SOPHISTICATED'
#     PRE_SEEDER = 'PRE_SEEDER'
#     FOUNDING_TEAM = 'FOUNDING_TEAM'
#
#     @staticmethod
#     def to_dict():
#         return {'SIMPLE': GON_PM_TYPE.SIMPLE,
#                 'SIMPLE_WITH_PROFIT_TAKING_ON_APY': GON_PM_TYPE.SIMPLE_WITH_PROFIT_TAKING_ON_APY,
#                 'CONSERVATIVE': GON_PM_TYPE.CONSERVATIVE,
#                 'BUY_AND_HOLD': GON_PM_TYPE.BUY_AND_HOLD,
#                 'LP_PROVIDER': GON_PM_TYPE.LP_PROVIDER,
#                 'SOPHISTICATED': GON_PM_TYPE.SOPHISTICATED,}